name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to your project directory
            # IMPORTANT: Make sure this path is correct on your Droplet!
            cd ~/font-previewer
            
            # Pull the latest changes from the main branch
            git pull origin main
            
            # Install/update dependencies
            npm install
            
            # Build the Next.js application for production
            npm run build
            
            # Restart the application with PM2
            # This command will restart the app if it's running,
            # or start it if it's not.
            pm2 restart font-previewer || pm2 start npm --name "font-previewer" -- start 